name: paso ci

on:
  workflow_call:
    outputs:
        IMAGEN:
            value: ${{ jobs.job-ci.outputs.IMAGEN }}

jobs:
  job-ci:
    outputs:
        IMAGEN: ${{ steps.taggear.outputs.nombre }}

    runs-on: [weeklyjaviergarcia]
    steps:
      - name: cargamos repositorio
        uses: actions/checkout@v4

      - name: taggeando la imagen de docker
        id: taggear
        uses: ./.github/actions/tag
        with:
          nombre_imagen: jga_angular

      - name: construyendo imagen
        run: docker build -t ${{ vars.DOCKERUSER }}/${{ steps.taggear.outputs.nombre }} .

      - name: login en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERUSER }}
          password: ${{ secrets.DOCKERTOKEN }}

      - name: subiendo la imagen al docker
        run: docker push ${{ vars.DOCKERUSER }}/${{ steps.taggear.outputs.nombre }}
