name: principal flujo ci/cd

on:
  push:
    branches:
      - main
      - development
  workflow_dispatch:

jobs:
  llamar_ci:
    uses: ./.github/workflows/paso_ci.yaml

  llamar_cd:
    needs: llamar_ci
    uses: ./.github/workflows/paso_cd.yaml
    with:
      ENTORNO: ${{ github.ref_name == 'main' && 'produccion' || 'desarrollo' }}
      IMAGEN: ${{ needs.llamar_ci.outputs.IMAGEN }}
      
  limpieza:
    needs: llamar_cd
    uses: ./.github/workflows/limpieza.yaml