name: principal flujo ci/cd

on:
  push:
    branches:
      - main
      - development
  workflow_dispatch:

jobs:
  llamar_ci:
    uses: ./.github/workflows/paso_ci.yaml
    secrets: inherit  # esto hereda los secretos en este trabajo

  llamar_cd:
    needs: llamar_ci
    uses: ./.github/workflows/paso_cd.yaml
    with:
      ENTORNO: ${{ github.ref_name == 'main' && 'produccion' || 'desarrollo' }}
      IMAGEN: ${{ needs.llamar_ci.outputs.IMAGEN }}

  limpieza:
    needs: llamar_cd
     # aunque falle cd lo hace
    if: always()   
    uses: ./.github/workflows/limpieza.yaml

    
